/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation SignIn($email: String!, $password: String!) {\n    signIn(input: { email: $email, password: $password }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n": typeof types.SignInDocument,
    "\n  mutation GoogleSignIn($idToken: String!) {\n    googleSignIn(input: { idToken: $idToken }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n": typeof types.GoogleSignInDocument,
    "\n  mutation SignUp($email: String!, $password: String!, $displayName: String) {\n    signUp(input: { email: $email, password: $password, displayName: $displayName }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n": typeof types.SignUpDocument,
    "\n  mutation SignOut {\n    signOut(input: {}) {\n      success\n    }\n  }\n": typeof types.SignOutDocument,
    "\n  mutation ConnectTradovate($apiKey: String!, $demo: Boolean) {\n    connectTradovate(input: { apiKey: $apiKey, demo: $demo }) {\n      brokerConnection {\n        id\n        broker\n        status\n        demoMode\n      }\n      errors\n    }\n  }\n": typeof types.ConnectTradovateDocument,
    "\n  mutation SyncTrades($accountId: ID!, $date: ISO8601Date) {\n    syncTrades(input: { accountId: $accountId, date: $date }) {\n      enqueued\n      errors\n    }\n  }\n": typeof types.SyncTradesDocument,
    "\n  mutation UpdateTradeJournal($id: ID!, $notes: String, $emotion: String, $screenshotUrl: String, $stopLoss: Float, $targetPrice: Float) {\n    updateTradeJournal(input: { id: $id, notes: $notes, emotion: $emotion, screenshotUrl: $screenshotUrl, stopLoss: $stopLoss, targetPrice: $targetPrice }) {\n      trade {\n        id\n        notes\n        emotion\n        screenshotUrl\n        stopLoss\n        targetPrice\n      }\n      errors\n    }\n  }\n": typeof types.UpdateTradeJournalDocument,
    "\n  mutation GradeSession($date: ISO8601Date!) {\n    gradeSession(input: { date: $date }) {\n      trades {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n": typeof types.GradeSessionDocument,
    "\n  mutation GradeTrade($id: ID!) {\n    gradeTrade(input: { id: $id }) {\n      trade {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n": typeof types.GradeTradeDocument,
    "\n  mutation GenerateDailyReport($date: ISO8601Date) {\n    generateDailyReport(input: { date: $date }) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n      }\n      errors\n    }\n  }\n": typeof types.GenerateDailyReportDocument,
    "\n  mutation GeneratePeriodReport($periodType: String!, $periodStart: ISO8601Date!) {\n    generatePeriodReport(input: { periodType: $periodType, periodStart: $periodStart }) {\n      report {\n        id\n        reportType\n        periodStart\n        periodEnd\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n": typeof types.GeneratePeriodReportDocument,
    "\n  mutation GenerateOverallReport {\n    generateOverallReport(input: {}) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n": typeof types.GenerateOverallReportDocument,
    "\n  mutation CreateCheckoutSession {\n    createCheckoutSession(input: {}) {\n      url\n      errors\n    }\n  }\n": typeof types.CreateCheckoutSessionDocument,
    "\n  mutation CreatePortalSession {\n    createPortalSession(input: {}) {\n      url\n      errors\n    }\n  }\n": typeof types.CreatePortalSessionDocument,
    "\n  mutation UpdateAccountRules($id: ID!, $dailyLossLimit: Float, $maxContracts: Int, $maxTradesPerSession: Int, $maxConsecutiveLosses: Int) {\n    updateAccountRules(input: {\n      id: $id,\n      dailyLossLimit: $dailyLossLimit,\n      maxContracts: $maxContracts,\n      maxTradesPerSession: $maxTradesPerSession,\n      maxConsecutiveLosses: $maxConsecutiveLosses\n    }) {\n      account {\n        id\n        rules\n      }\n      errors\n    }\n  }\n": typeof types.UpdateAccountRulesDocument,
    "\n  mutation CreateAccount($firmName: String!, $name: String!, $accountType: String!, $balance: Float!, $commissionPerContract: Float) {\n    createAccount(input: { firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n": typeof types.CreateAccountDocument,
    "\n  mutation UpdateAccount($id: ID!, $firmName: String, $name: String, $accountType: String, $balance: Float, $commissionPerContract: Float) {\n    updateAccount(input: { id: $id, firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n": typeof types.UpdateAccountDocument,
    "\n  mutation DeleteAccount($id: ID!) {\n    deleteAccount(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n": typeof types.DeleteAccountDocument,
    "\n  mutation DeleteTrade($id: ID!) {\n    deleteTrade(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n": typeof types.DeleteTradeDocument,
    "\n  mutation ImportCsv($accountId: ID!, $csvData: String!, $platform: String) {\n    importCsv(input: { accountId: $accountId, csvData: $csvData, platform: $platform }) {\n      tradesImported\n      errors\n    }\n  }\n": typeof types.ImportCsvDocument,
    "\n  mutation SaveTradingPlan($playbook: JSON, $rules: JSON, $weeklyIntention: String) {\n    saveTradingPlan(input: { playbook: $playbook, rules: $rules, weeklyIntention: $weeklyIntention }) {\n      tradingPlan {\n        id\n        playbook\n        rules\n        weeklyIntention\n      }\n      errors\n    }\n  }\n": typeof types.SaveTradingPlanDocument,
    "\n  mutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n    changePassword(input: { currentPassword: $currentPassword, newPassword: $newPassword }) {\n      success\n      errors\n    }\n  }\n": typeof types.ChangePasswordDocument,
    "\n  mutation UpdateUserSettings($displayName: String, $phone: String, $smsEnabled: Boolean) {\n    updateUserSettings(input: { displayName: $displayName, phone: $phone, smsEnabled: $smsEnabled }) {\n      user {\n        id\n        email\n        displayName\n        phone\n        smsEnabled\n      }\n      errors\n    }\n  }\n": typeof types.UpdateUserSettingsDocument,
    "\n  mutation CreateTrade(\n    $instrument: String!\n    $side: String!\n    $quantity: Int!\n    $entryPrice: Float!\n    $exitPrice: Float\n    $stopLoss: Float\n    $targetPrice: Float\n    $netPnl: Float\n    $enteredAt: ISO8601DateTime\n    $exitedAt: ISO8601DateTime\n    $notes: String\n    $emotion: String\n    $sessionDate: ISO8601Date\n  ) {\n    createTrade(input: {\n      instrument: $instrument\n      side: $side\n      quantity: $quantity\n      entryPrice: $entryPrice\n      exitPrice: $exitPrice\n      stopLoss: $stopLoss\n      targetPrice: $targetPrice\n      netPnl: $netPnl\n      enteredAt: $enteredAt\n      exitedAt: $exitedAt\n      notes: $notes\n      emotion: $emotion\n      sessionDate: $sessionDate\n    }) {\n      trade {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        netPnl\n        grade\n        emotion\n        notes\n        enteredAt\n        exitedAt\n        status\n      }\n      errors\n    }\n  }\n": typeof types.CreateTradeDocument,
    "\n  query Me {\n    me {\n      id\n      email\n      displayName\n      phone\n      smsEnabled\n    }\n  }\n": typeof types.MeDocument,
    "\n  query MyTradingPlan {\n    myTradingPlan {\n      id\n      playbook\n      rules\n      weeklyIntention\n      updatedAt\n    }\n  }\n": typeof types.MyTradingPlanDocument,
    "\n  query ListAccounts {\n    accounts {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      commissionPerContract\n    }\n  }\n": typeof types.ListAccountsDocument,
    "\n  query CurrentAccount {\n    currentAccount {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      totalPnl\n      currentBalance\n      percentReturn\n      totalTrades\n      tradingDays\n      firstSessionDate\n      winRate\n      profitFactor\n      avgDayPnl\n      bestDayPnl\n      worstDayPnl\n      avgDisciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      revengeTradeRate\n      recentViolations\n      tradingSessions {\n        id\n        sessionDate\n        netPnl\n      }\n      recentTrades {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        targetPrice\n        netPnl\n        grade\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        coachingNotes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n      }\n    }\n  }\n": typeof types.CurrentAccountDocument,
    "\n  query TodaySession($date: ISO8601Date) {\n    tradingSession(date: $date) {\n      id\n      sessionDate\n      marketSession\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n      analyticsPayload\n      trades {\n        id\n        brokerTradeId\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        netPnl\n        grade\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        notes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        coachingNotes\n        compositeScore\n        offPlaybook\n      }\n      ruleViolations {\n        id\n        ruleType\n        description\n        severity\n        impactPnl\n      }\n    }\n  }\n": typeof types.TodaySessionDocument,
    "\n  query PaginatedTrades($limit: Int, $offset: Int) {\n    trades(limit: $limit, offset: $offset) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      targetPrice\n      netPnl\n      grade\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      status\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      coachingNotes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      compositeScore\n    }\n  }\n": typeof types.PaginatedTradesDocument,
    "\n  query TradeDetail($id: ID!) {\n    trade(id: $id) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      netPnl\n      grade\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      notes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      coachingNotes\n      compositeScore\n    }\n  }\n": typeof types.TradeDetailDocument,
    "\n  query ListReports($type: String, $limit: Int) {\n    reports(type: $type, limit: $limit) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n": typeof types.ListReportsDocument,
    "\n  query WeeklyReport($weekOf: ISO8601Date!) {\n    weeklyReport(weekOf: $weekOf) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n": typeof types.WeeklyReportDocument,
    "\n  query SessionAnalytics($id: ID!) {\n    sessionAnalytics(id: $id) {\n      disciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      earlyExitRate\n      revengeTradeCount\n      behavioralFlags\n      timeOfDayBreakdown\n      rDistribution\n    }\n  }\n": typeof types.SessionAnalyticsDocument,
    "\n  query WeekSessions($weekOf: ISO8601Date!) {\n    weekSessions(weekOf: $weekOf) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      winRate\n      disciplineScore\n    }\n  }\n": typeof types.WeekSessionsDocument,
    "\n  query MonthSessions($year: Int!, $month: Int!) {\n    monthSessions(year: $year, month: $month) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      disciplineScore\n    }\n  }\n": typeof types.MonthSessionsDocument,
    "\n  subscription OnTradeSynced($accountId: ID!) {\n    tradeSynced(accountId: $accountId) {\n      id\n      instrument\n      side\n      netPnl\n      grade\n      enteredAt\n    }\n  }\n": typeof types.OnTradeSyncedDocument,
    "\n  subscription OnReportGenerated($accountId: ID!) {\n    reportGenerated(accountId: $accountId) {\n      id\n      reportType\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n    }\n  }\n": typeof types.OnReportGeneratedDocument,
    "\n  subscription OnSessionUpdated($sessionId: ID!) {\n    sessionUpdated(sessionId: $sessionId) {\n      id\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n    }\n  }\n": typeof types.OnSessionUpdatedDocument,
};
const documents: Documents = {
    "\n  mutation SignIn($email: String!, $password: String!) {\n    signIn(input: { email: $email, password: $password }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n": types.SignInDocument,
    "\n  mutation GoogleSignIn($idToken: String!) {\n    googleSignIn(input: { idToken: $idToken }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n": types.GoogleSignInDocument,
    "\n  mutation SignUp($email: String!, $password: String!, $displayName: String) {\n    signUp(input: { email: $email, password: $password, displayName: $displayName }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n": types.SignUpDocument,
    "\n  mutation SignOut {\n    signOut(input: {}) {\n      success\n    }\n  }\n": types.SignOutDocument,
    "\n  mutation ConnectTradovate($apiKey: String!, $demo: Boolean) {\n    connectTradovate(input: { apiKey: $apiKey, demo: $demo }) {\n      brokerConnection {\n        id\n        broker\n        status\n        demoMode\n      }\n      errors\n    }\n  }\n": types.ConnectTradovateDocument,
    "\n  mutation SyncTrades($accountId: ID!, $date: ISO8601Date) {\n    syncTrades(input: { accountId: $accountId, date: $date }) {\n      enqueued\n      errors\n    }\n  }\n": types.SyncTradesDocument,
    "\n  mutation UpdateTradeJournal($id: ID!, $notes: String, $emotion: String, $screenshotUrl: String, $stopLoss: Float, $targetPrice: Float) {\n    updateTradeJournal(input: { id: $id, notes: $notes, emotion: $emotion, screenshotUrl: $screenshotUrl, stopLoss: $stopLoss, targetPrice: $targetPrice }) {\n      trade {\n        id\n        notes\n        emotion\n        screenshotUrl\n        stopLoss\n        targetPrice\n      }\n      errors\n    }\n  }\n": types.UpdateTradeJournalDocument,
    "\n  mutation GradeSession($date: ISO8601Date!) {\n    gradeSession(input: { date: $date }) {\n      trades {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n": types.GradeSessionDocument,
    "\n  mutation GradeTrade($id: ID!) {\n    gradeTrade(input: { id: $id }) {\n      trade {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n": types.GradeTradeDocument,
    "\n  mutation GenerateDailyReport($date: ISO8601Date) {\n    generateDailyReport(input: { date: $date }) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n      }\n      errors\n    }\n  }\n": types.GenerateDailyReportDocument,
    "\n  mutation GeneratePeriodReport($periodType: String!, $periodStart: ISO8601Date!) {\n    generatePeriodReport(input: { periodType: $periodType, periodStart: $periodStart }) {\n      report {\n        id\n        reportType\n        periodStart\n        periodEnd\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n": types.GeneratePeriodReportDocument,
    "\n  mutation GenerateOverallReport {\n    generateOverallReport(input: {}) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n": types.GenerateOverallReportDocument,
    "\n  mutation CreateCheckoutSession {\n    createCheckoutSession(input: {}) {\n      url\n      errors\n    }\n  }\n": types.CreateCheckoutSessionDocument,
    "\n  mutation CreatePortalSession {\n    createPortalSession(input: {}) {\n      url\n      errors\n    }\n  }\n": types.CreatePortalSessionDocument,
    "\n  mutation UpdateAccountRules($id: ID!, $dailyLossLimit: Float, $maxContracts: Int, $maxTradesPerSession: Int, $maxConsecutiveLosses: Int) {\n    updateAccountRules(input: {\n      id: $id,\n      dailyLossLimit: $dailyLossLimit,\n      maxContracts: $maxContracts,\n      maxTradesPerSession: $maxTradesPerSession,\n      maxConsecutiveLosses: $maxConsecutiveLosses\n    }) {\n      account {\n        id\n        rules\n      }\n      errors\n    }\n  }\n": types.UpdateAccountRulesDocument,
    "\n  mutation CreateAccount($firmName: String!, $name: String!, $accountType: String!, $balance: Float!, $commissionPerContract: Float) {\n    createAccount(input: { firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n": types.CreateAccountDocument,
    "\n  mutation UpdateAccount($id: ID!, $firmName: String, $name: String, $accountType: String, $balance: Float, $commissionPerContract: Float) {\n    updateAccount(input: { id: $id, firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n": types.UpdateAccountDocument,
    "\n  mutation DeleteAccount($id: ID!) {\n    deleteAccount(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n": types.DeleteAccountDocument,
    "\n  mutation DeleteTrade($id: ID!) {\n    deleteTrade(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n": types.DeleteTradeDocument,
    "\n  mutation ImportCsv($accountId: ID!, $csvData: String!, $platform: String) {\n    importCsv(input: { accountId: $accountId, csvData: $csvData, platform: $platform }) {\n      tradesImported\n      errors\n    }\n  }\n": types.ImportCsvDocument,
    "\n  mutation SaveTradingPlan($playbook: JSON, $rules: JSON, $weeklyIntention: String) {\n    saveTradingPlan(input: { playbook: $playbook, rules: $rules, weeklyIntention: $weeklyIntention }) {\n      tradingPlan {\n        id\n        playbook\n        rules\n        weeklyIntention\n      }\n      errors\n    }\n  }\n": types.SaveTradingPlanDocument,
    "\n  mutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n    changePassword(input: { currentPassword: $currentPassword, newPassword: $newPassword }) {\n      success\n      errors\n    }\n  }\n": types.ChangePasswordDocument,
    "\n  mutation UpdateUserSettings($displayName: String, $phone: String, $smsEnabled: Boolean) {\n    updateUserSettings(input: { displayName: $displayName, phone: $phone, smsEnabled: $smsEnabled }) {\n      user {\n        id\n        email\n        displayName\n        phone\n        smsEnabled\n      }\n      errors\n    }\n  }\n": types.UpdateUserSettingsDocument,
    "\n  mutation CreateTrade(\n    $instrument: String!\n    $side: String!\n    $quantity: Int!\n    $entryPrice: Float!\n    $exitPrice: Float\n    $stopLoss: Float\n    $targetPrice: Float\n    $netPnl: Float\n    $enteredAt: ISO8601DateTime\n    $exitedAt: ISO8601DateTime\n    $notes: String\n    $emotion: String\n    $sessionDate: ISO8601Date\n  ) {\n    createTrade(input: {\n      instrument: $instrument\n      side: $side\n      quantity: $quantity\n      entryPrice: $entryPrice\n      exitPrice: $exitPrice\n      stopLoss: $stopLoss\n      targetPrice: $targetPrice\n      netPnl: $netPnl\n      enteredAt: $enteredAt\n      exitedAt: $exitedAt\n      notes: $notes\n      emotion: $emotion\n      sessionDate: $sessionDate\n    }) {\n      trade {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        netPnl\n        grade\n        emotion\n        notes\n        enteredAt\n        exitedAt\n        status\n      }\n      errors\n    }\n  }\n": types.CreateTradeDocument,
    "\n  query Me {\n    me {\n      id\n      email\n      displayName\n      phone\n      smsEnabled\n    }\n  }\n": types.MeDocument,
    "\n  query MyTradingPlan {\n    myTradingPlan {\n      id\n      playbook\n      rules\n      weeklyIntention\n      updatedAt\n    }\n  }\n": types.MyTradingPlanDocument,
    "\n  query ListAccounts {\n    accounts {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      commissionPerContract\n    }\n  }\n": types.ListAccountsDocument,
    "\n  query CurrentAccount {\n    currentAccount {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      totalPnl\n      currentBalance\n      percentReturn\n      totalTrades\n      tradingDays\n      firstSessionDate\n      winRate\n      profitFactor\n      avgDayPnl\n      bestDayPnl\n      worstDayPnl\n      avgDisciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      revengeTradeRate\n      recentViolations\n      tradingSessions {\n        id\n        sessionDate\n        netPnl\n      }\n      recentTrades {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        targetPrice\n        netPnl\n        grade\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        coachingNotes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n      }\n    }\n  }\n": types.CurrentAccountDocument,
    "\n  query TodaySession($date: ISO8601Date) {\n    tradingSession(date: $date) {\n      id\n      sessionDate\n      marketSession\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n      analyticsPayload\n      trades {\n        id\n        brokerTradeId\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        netPnl\n        grade\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        notes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        coachingNotes\n        compositeScore\n        offPlaybook\n      }\n      ruleViolations {\n        id\n        ruleType\n        description\n        severity\n        impactPnl\n      }\n    }\n  }\n": types.TodaySessionDocument,
    "\n  query PaginatedTrades($limit: Int, $offset: Int) {\n    trades(limit: $limit, offset: $offset) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      targetPrice\n      netPnl\n      grade\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      status\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      coachingNotes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      compositeScore\n    }\n  }\n": types.PaginatedTradesDocument,
    "\n  query TradeDetail($id: ID!) {\n    trade(id: $id) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      netPnl\n      grade\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      notes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      coachingNotes\n      compositeScore\n    }\n  }\n": types.TradeDetailDocument,
    "\n  query ListReports($type: String, $limit: Int) {\n    reports(type: $type, limit: $limit) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n": types.ListReportsDocument,
    "\n  query WeeklyReport($weekOf: ISO8601Date!) {\n    weeklyReport(weekOf: $weekOf) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n": types.WeeklyReportDocument,
    "\n  query SessionAnalytics($id: ID!) {\n    sessionAnalytics(id: $id) {\n      disciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      earlyExitRate\n      revengeTradeCount\n      behavioralFlags\n      timeOfDayBreakdown\n      rDistribution\n    }\n  }\n": types.SessionAnalyticsDocument,
    "\n  query WeekSessions($weekOf: ISO8601Date!) {\n    weekSessions(weekOf: $weekOf) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      winRate\n      disciplineScore\n    }\n  }\n": types.WeekSessionsDocument,
    "\n  query MonthSessions($year: Int!, $month: Int!) {\n    monthSessions(year: $year, month: $month) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      disciplineScore\n    }\n  }\n": types.MonthSessionsDocument,
    "\n  subscription OnTradeSynced($accountId: ID!) {\n    tradeSynced(accountId: $accountId) {\n      id\n      instrument\n      side\n      netPnl\n      grade\n      enteredAt\n    }\n  }\n": types.OnTradeSyncedDocument,
    "\n  subscription OnReportGenerated($accountId: ID!) {\n    reportGenerated(accountId: $accountId) {\n      id\n      reportType\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n    }\n  }\n": types.OnReportGeneratedDocument,
    "\n  subscription OnSessionUpdated($sessionId: ID!) {\n    sessionUpdated(sessionId: $sessionId) {\n      id\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n    }\n  }\n": types.OnSessionUpdatedDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SignIn($email: String!, $password: String!) {\n    signIn(input: { email: $email, password: $password }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation SignIn($email: String!, $password: String!) {\n    signIn(input: { email: $email, password: $password }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GoogleSignIn($idToken: String!) {\n    googleSignIn(input: { idToken: $idToken }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation GoogleSignIn($idToken: String!) {\n    googleSignIn(input: { idToken: $idToken }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SignUp($email: String!, $password: String!, $displayName: String) {\n    signUp(input: { email: $email, password: $password, displayName: $displayName }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation SignUp($email: String!, $password: String!, $displayName: String) {\n    signUp(input: { email: $email, password: $password, displayName: $displayName }) {\n      token\n      user {\n        id\n        email\n        displayName\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SignOut {\n    signOut(input: {}) {\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation SignOut {\n    signOut(input: {}) {\n      success\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ConnectTradovate($apiKey: String!, $demo: Boolean) {\n    connectTradovate(input: { apiKey: $apiKey, demo: $demo }) {\n      brokerConnection {\n        id\n        broker\n        status\n        demoMode\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation ConnectTradovate($apiKey: String!, $demo: Boolean) {\n    connectTradovate(input: { apiKey: $apiKey, demo: $demo }) {\n      brokerConnection {\n        id\n        broker\n        status\n        demoMode\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SyncTrades($accountId: ID!, $date: ISO8601Date) {\n    syncTrades(input: { accountId: $accountId, date: $date }) {\n      enqueued\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation SyncTrades($accountId: ID!, $date: ISO8601Date) {\n    syncTrades(input: { accountId: $accountId, date: $date }) {\n      enqueued\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateTradeJournal($id: ID!, $notes: String, $emotion: String, $screenshotUrl: String, $stopLoss: Float, $targetPrice: Float) {\n    updateTradeJournal(input: { id: $id, notes: $notes, emotion: $emotion, screenshotUrl: $screenshotUrl, stopLoss: $stopLoss, targetPrice: $targetPrice }) {\n      trade {\n        id\n        notes\n        emotion\n        screenshotUrl\n        stopLoss\n        targetPrice\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateTradeJournal($id: ID!, $notes: String, $emotion: String, $screenshotUrl: String, $stopLoss: Float, $targetPrice: Float) {\n    updateTradeJournal(input: { id: $id, notes: $notes, emotion: $emotion, screenshotUrl: $screenshotUrl, stopLoss: $stopLoss, targetPrice: $targetPrice }) {\n      trade {\n        id\n        notes\n        emotion\n        screenshotUrl\n        stopLoss\n        targetPrice\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GradeSession($date: ISO8601Date!) {\n    gradeSession(input: { date: $date }) {\n      trades {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation GradeSession($date: ISO8601Date!) {\n    gradeSession(input: { date: $date }) {\n      trades {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GradeTrade($id: ID!) {\n    gradeTrade(input: { id: $id }) {\n      trade {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation GradeTrade($id: ID!) {\n    gradeTrade(input: { id: $id }) {\n      trade {\n        id\n        grade\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n        coachingNotes\n        offPlaybook\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GenerateDailyReport($date: ISO8601Date) {\n    generateDailyReport(input: { date: $date }) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateDailyReport($date: ISO8601Date) {\n    generateDailyReport(input: { date: $date }) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GeneratePeriodReport($periodType: String!, $periodStart: ISO8601Date!) {\n    generatePeriodReport(input: { periodType: $periodType, periodStart: $periodStart }) {\n      report {\n        id\n        reportType\n        periodStart\n        periodEnd\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation GeneratePeriodReport($periodType: String!, $periodStart: ISO8601Date!) {\n    generatePeriodReport(input: { periodType: $periodType, periodStart: $periodStart }) {\n      report {\n        id\n        reportType\n        periodStart\n        periodEnd\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GenerateOverallReport {\n    generateOverallReport(input: {}) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateOverallReport {\n    generateOverallReport(input: {}) {\n      report {\n        id\n        reportType\n        aiSummary\n        keyInsights\n        improvementAreas\n        statsSnapshot\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateCheckoutSession {\n    createCheckoutSession(input: {}) {\n      url\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation CreateCheckoutSession {\n    createCheckoutSession(input: {}) {\n      url\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreatePortalSession {\n    createPortalSession(input: {}) {\n      url\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePortalSession {\n    createPortalSession(input: {}) {\n      url\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateAccountRules($id: ID!, $dailyLossLimit: Float, $maxContracts: Int, $maxTradesPerSession: Int, $maxConsecutiveLosses: Int) {\n    updateAccountRules(input: {\n      id: $id,\n      dailyLossLimit: $dailyLossLimit,\n      maxContracts: $maxContracts,\n      maxTradesPerSession: $maxTradesPerSession,\n      maxConsecutiveLosses: $maxConsecutiveLosses\n    }) {\n      account {\n        id\n        rules\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateAccountRules($id: ID!, $dailyLossLimit: Float, $maxContracts: Int, $maxTradesPerSession: Int, $maxConsecutiveLosses: Int) {\n    updateAccountRules(input: {\n      id: $id,\n      dailyLossLimit: $dailyLossLimit,\n      maxContracts: $maxContracts,\n      maxTradesPerSession: $maxTradesPerSession,\n      maxConsecutiveLosses: $maxConsecutiveLosses\n    }) {\n      account {\n        id\n        rules\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateAccount($firmName: String!, $name: String!, $accountType: String!, $balance: Float!, $commissionPerContract: Float) {\n    createAccount(input: { firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation CreateAccount($firmName: String!, $name: String!, $accountType: String!, $balance: Float!, $commissionPerContract: Float) {\n    createAccount(input: { firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateAccount($id: ID!, $firmName: String, $name: String, $accountType: String, $balance: Float, $commissionPerContract: Float) {\n    updateAccount(input: { id: $id, firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateAccount($id: ID!, $firmName: String, $name: String, $accountType: String, $balance: Float, $commissionPerContract: Float) {\n    updateAccount(input: { id: $id, firmName: $firmName, name: $name, accountType: $accountType, balance: $balance, commissionPerContract: $commissionPerContract }) {\n      account {\n        id\n        name\n        firmName\n        accountType\n        balance\n        commissionPerContract\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteAccount($id: ID!) {\n    deleteAccount(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteAccount($id: ID!) {\n    deleteAccount(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteTrade($id: ID!) {\n    deleteTrade(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteTrade($id: ID!) {\n    deleteTrade(input: { id: $id }) {\n      success\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ImportCsv($accountId: ID!, $csvData: String!, $platform: String) {\n    importCsv(input: { accountId: $accountId, csvData: $csvData, platform: $platform }) {\n      tradesImported\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation ImportCsv($accountId: ID!, $csvData: String!, $platform: String) {\n    importCsv(input: { accountId: $accountId, csvData: $csvData, platform: $platform }) {\n      tradesImported\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SaveTradingPlan($playbook: JSON, $rules: JSON, $weeklyIntention: String) {\n    saveTradingPlan(input: { playbook: $playbook, rules: $rules, weeklyIntention: $weeklyIntention }) {\n      tradingPlan {\n        id\n        playbook\n        rules\n        weeklyIntention\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation SaveTradingPlan($playbook: JSON, $rules: JSON, $weeklyIntention: String) {\n    saveTradingPlan(input: { playbook: $playbook, rules: $rules, weeklyIntention: $weeklyIntention }) {\n      tradingPlan {\n        id\n        playbook\n        rules\n        weeklyIntention\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n    changePassword(input: { currentPassword: $currentPassword, newPassword: $newPassword }) {\n      success\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n    changePassword(input: { currentPassword: $currentPassword, newPassword: $newPassword }) {\n      success\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateUserSettings($displayName: String, $phone: String, $smsEnabled: Boolean) {\n    updateUserSettings(input: { displayName: $displayName, phone: $phone, smsEnabled: $smsEnabled }) {\n      user {\n        id\n        email\n        displayName\n        phone\n        smsEnabled\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateUserSettings($displayName: String, $phone: String, $smsEnabled: Boolean) {\n    updateUserSettings(input: { displayName: $displayName, phone: $phone, smsEnabled: $smsEnabled }) {\n      user {\n        id\n        email\n        displayName\n        phone\n        smsEnabled\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateTrade(\n    $instrument: String!\n    $side: String!\n    $quantity: Int!\n    $entryPrice: Float!\n    $exitPrice: Float\n    $stopLoss: Float\n    $targetPrice: Float\n    $netPnl: Float\n    $enteredAt: ISO8601DateTime\n    $exitedAt: ISO8601DateTime\n    $notes: String\n    $emotion: String\n    $sessionDate: ISO8601Date\n  ) {\n    createTrade(input: {\n      instrument: $instrument\n      side: $side\n      quantity: $quantity\n      entryPrice: $entryPrice\n      exitPrice: $exitPrice\n      stopLoss: $stopLoss\n      targetPrice: $targetPrice\n      netPnl: $netPnl\n      enteredAt: $enteredAt\n      exitedAt: $exitedAt\n      notes: $notes\n      emotion: $emotion\n      sessionDate: $sessionDate\n    }) {\n      trade {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        netPnl\n        grade\n        emotion\n        notes\n        enteredAt\n        exitedAt\n        status\n      }\n      errors\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTrade(\n    $instrument: String!\n    $side: String!\n    $quantity: Int!\n    $entryPrice: Float!\n    $exitPrice: Float\n    $stopLoss: Float\n    $targetPrice: Float\n    $netPnl: Float\n    $enteredAt: ISO8601DateTime\n    $exitedAt: ISO8601DateTime\n    $notes: String\n    $emotion: String\n    $sessionDate: ISO8601Date\n  ) {\n    createTrade(input: {\n      instrument: $instrument\n      side: $side\n      quantity: $quantity\n      entryPrice: $entryPrice\n      exitPrice: $exitPrice\n      stopLoss: $stopLoss\n      targetPrice: $targetPrice\n      netPnl: $netPnl\n      enteredAt: $enteredAt\n      exitedAt: $exitedAt\n      notes: $notes\n      emotion: $emotion\n      sessionDate: $sessionDate\n    }) {\n      trade {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        netPnl\n        grade\n        emotion\n        notes\n        enteredAt\n        exitedAt\n        status\n      }\n      errors\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Me {\n    me {\n      id\n      email\n      displayName\n      phone\n      smsEnabled\n    }\n  }\n"): (typeof documents)["\n  query Me {\n    me {\n      id\n      email\n      displayName\n      phone\n      smsEnabled\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query MyTradingPlan {\n    myTradingPlan {\n      id\n      playbook\n      rules\n      weeklyIntention\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query MyTradingPlan {\n    myTradingPlan {\n      id\n      playbook\n      rules\n      weeklyIntention\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ListAccounts {\n    accounts {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      commissionPerContract\n    }\n  }\n"): (typeof documents)["\n  query ListAccounts {\n    accounts {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      commissionPerContract\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query CurrentAccount {\n    currentAccount {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      totalPnl\n      currentBalance\n      percentReturn\n      totalTrades\n      tradingDays\n      firstSessionDate\n      winRate\n      profitFactor\n      avgDayPnl\n      bestDayPnl\n      worstDayPnl\n      avgDisciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      revengeTradeRate\n      recentViolations\n      tradingSessions {\n        id\n        sessionDate\n        netPnl\n      }\n      recentTrades {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        targetPrice\n        netPnl\n        grade\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        coachingNotes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n      }\n    }\n  }\n"): (typeof documents)["\n  query CurrentAccount {\n    currentAccount {\n      id\n      name\n      accountType\n      firmName\n      balance\n      buyingPower\n      dailyPnl\n      rules\n      totalPnl\n      currentBalance\n      percentReturn\n      totalTrades\n      tradingDays\n      firstSessionDate\n      winRate\n      profitFactor\n      avgDayPnl\n      bestDayPnl\n      worstDayPnl\n      avgDisciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      revengeTradeRate\n      recentViolations\n      tradingSessions {\n        id\n        sessionDate\n        netPnl\n      }\n      recentTrades {\n        id\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        targetPrice\n        netPnl\n        grade\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        coachingNotes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        compositeScore\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query TodaySession($date: ISO8601Date) {\n    tradingSession(date: $date) {\n      id\n      sessionDate\n      marketSession\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n      analyticsPayload\n      trades {\n        id\n        brokerTradeId\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        netPnl\n        grade\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        notes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        coachingNotes\n        compositeScore\n        offPlaybook\n      }\n      ruleViolations {\n        id\n        ruleType\n        description\n        severity\n        impactPnl\n      }\n    }\n  }\n"): (typeof documents)["\n  query TodaySession($date: ISO8601Date) {\n    tradingSession(date: $date) {\n      id\n      sessionDate\n      marketSession\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n      analyticsPayload\n      trades {\n        id\n        brokerTradeId\n        instrument\n        side\n        quantity\n        entryPrice\n        exitPrice\n        stopLoss\n        netPnl\n        grade\n        isRevengeTrade\n        emotion\n        screenshotUrl\n        rMultiple\n        durationMinutes\n        enteredAt\n        exitedAt\n        status\n        notes\n        setupScore\n        entryScore\n        riskScore\n        mgmtScore\n        coachingNotes\n        compositeScore\n        offPlaybook\n      }\n      ruleViolations {\n        id\n        ruleType\n        description\n        severity\n        impactPnl\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query PaginatedTrades($limit: Int, $offset: Int) {\n    trades(limit: $limit, offset: $offset) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      targetPrice\n      netPnl\n      grade\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      status\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      coachingNotes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      compositeScore\n    }\n  }\n"): (typeof documents)["\n  query PaginatedTrades($limit: Int, $offset: Int) {\n    trades(limit: $limit, offset: $offset) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      targetPrice\n      netPnl\n      grade\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      status\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      coachingNotes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      compositeScore\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query TradeDetail($id: ID!) {\n    trade(id: $id) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      netPnl\n      grade\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      notes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      coachingNotes\n      compositeScore\n    }\n  }\n"): (typeof documents)["\n  query TradeDetail($id: ID!) {\n    trade(id: $id) {\n      id\n      instrument\n      side\n      quantity\n      entryPrice\n      exitPrice\n      stopLoss\n      netPnl\n      grade\n      isRevengeTrade\n      emotion\n      screenshotUrl\n      rMultiple\n      durationMinutes\n      enteredAt\n      exitedAt\n      notes\n      setupScore\n      entryScore\n      riskScore\n      mgmtScore\n      coachingNotes\n      compositeScore\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ListReports($type: String, $limit: Int) {\n    reports(type: $type, limit: $limit) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query ListReports($type: String, $limit: Int) {\n    reports(type: $type, limit: $limit) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query WeeklyReport($weekOf: ISO8601Date!) {\n    weeklyReport(weekOf: $weekOf) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query WeeklyReport($weekOf: ISO8601Date!) {\n    weeklyReport(weekOf: $weekOf) {\n      id\n      reportType\n      periodStart\n      periodEnd\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query SessionAnalytics($id: ID!) {\n    sessionAnalytics(id: $id) {\n      disciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      earlyExitRate\n      revengeTradeCount\n      behavioralFlags\n      timeOfDayBreakdown\n      rDistribution\n    }\n  }\n"): (typeof documents)["\n  query SessionAnalytics($id: ID!) {\n    sessionAnalytics(id: $id) {\n      disciplineScore\n      entryPrecision\n      stopDiscipline\n      tradeManagement\n      earlyExitRate\n      revengeTradeCount\n      behavioralFlags\n      timeOfDayBreakdown\n      rDistribution\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query WeekSessions($weekOf: ISO8601Date!) {\n    weekSessions(weekOf: $weekOf) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      winRate\n      disciplineScore\n    }\n  }\n"): (typeof documents)["\n  query WeekSessions($weekOf: ISO8601Date!) {\n    weekSessions(weekOf: $weekOf) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      winRate\n      disciplineScore\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query MonthSessions($year: Int!, $month: Int!) {\n    monthSessions(year: $year, month: $month) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      disciplineScore\n    }\n  }\n"): (typeof documents)["\n  query MonthSessions($year: Int!, $month: Int!) {\n    monthSessions(year: $year, month: $month) {\n      id\n      sessionDate\n      netPnl\n      tradeCount\n      disciplineScore\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnTradeSynced($accountId: ID!) {\n    tradeSynced(accountId: $accountId) {\n      id\n      instrument\n      side\n      netPnl\n      grade\n      enteredAt\n    }\n  }\n"): (typeof documents)["\n  subscription OnTradeSynced($accountId: ID!) {\n    tradeSynced(accountId: $accountId) {\n      id\n      instrument\n      side\n      netPnl\n      grade\n      enteredAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnReportGenerated($accountId: ID!) {\n    reportGenerated(accountId: $accountId) {\n      id\n      reportType\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n    }\n  }\n"): (typeof documents)["\n  subscription OnReportGenerated($accountId: ID!) {\n    reportGenerated(accountId: $accountId) {\n      id\n      reportType\n      aiSummary\n      keyInsights\n      improvementAreas\n      statsSnapshot\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnSessionUpdated($sessionId: ID!) {\n    sessionUpdated(sessionId: $sessionId) {\n      id\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n    }\n  }\n"): (typeof documents)["\n  subscription OnSessionUpdated($sessionId: ID!) {\n    sessionUpdated(sessionId: $sessionId) {\n      id\n      netPnl\n      disciplineScore\n      winRate\n      profitFactor\n      tradeCount\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;